<?php
declare(strict_types=1);
$user = current_user();
$tahun = year_value();
$canViewAll = user_can('view_all_targets');
$selectedUserId = $canViewAll ? (int)($_GET['user_id'] ?? $_POST['user_id'] ?? 0) : (int)$user['id'];
function evkin_decode_analysis(?string $value): array {
    $defaults=['kendala'=>'','upaya'=>'','strategi'=>'','solusi'=>''];
    $decoded=json_decode((string)$value,true);
    if (is_array($decoded) && isset($decoded['analysis'])) return array_merge($defaults,(array)$decoded['analysis']);
    if (trim((string)$value)!=='') $defaults['kendala']=(string)$value;
    return $defaults;
}
if ($_SERVER['REQUEST_METHOD']==='POST') {
    $targetId=(int)($_POST['target_id']??0); $tw=max(1,min(12,(int)($_POST['triwulan']??1)));
    $analysis=[]; foreach(['kendala','upaya','strategi','solusi'] as $field) $analysis[$field]=trim((string)($_POST[$field]??''));
    $check=db()->prepare('SELECT * FROM target_kinerja WHERE id=:id AND tahun=:tahun'); $check->execute(['id'=>$targetId,'tahun'=>$tahun]); $targetRow=$check->fetch();
    if(!$targetRow || !can_manage_target_row($targetRow)){flash('Indikator tidak valid atau bukan milik pengguna yang dapat Anda kelola.','error');}
    elseif(in_array('',array_values($analysis),true)){flash('Kendala, Upaya, Strategi, dan Solusi wajib diisi.','error');}
    else { $trend=achievement_trend($targetRow,$tw); $payload=json_encode(['version'=>2,'analysis'=>$analysis],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); $stmt=db()->prepare('INSERT INTO evaluasi (target_id,triwulan,jenis,narasi) VALUES (:target_id,:triwulan,:jenis,:narasi)'); $stmt->execute(['target_id'=>$targetId,'triwulan'=>$tw,'jenis'=>$trend['jenis'],'narasi'=>$payload]); flash('Analisis EvKin tersimpan.'); }
    header('Location: index.php?page=evaluasi&tahun='.$tahun.'&triwulan='.$tw.($selectedUserId>0?'&user_id='.$selectedUserId:'')); exit;
}
$owners=[]; if($canViewAll)$owners=db()->query('SELECT id,nama,role,unit FROM users WHERE status="active" ORDER BY unit,role,nama')->fetchAll();
$selectedTw=max(1,min(12,(int)($_GET['triwulan']??1)));
$targetQuery='SELECT tk.*,u.nama owner_nama,u.role owner_role FROM target_kinerja tk LEFT JOIN users u ON u.id=tk.user_id WHERE tk.tahun=:tahun'; $targetParams=['tahun'=>$tahun];
if($canViewAll&&$selectedUserId>0){$targetQuery.=' AND tk.user_id=:user_id';$targetParams['user_id']=$selectedUserId;}elseif(!$canViewAll){$targetQuery.=' AND tk.user_id=:user_id';$targetParams['user_id']=(int)$user['id'];}
$targetQuery.=' ORDER BY u.unit,u.role,u.nama,tk.id';$targetStmt=db()->prepare($targetQuery);$targetStmt->execute($targetParams);$targets=$targetStmt->fetchAll();
$evaluationMap=[];$mapStmt=db()->query('SELECT target_id,triwulan,COUNT(*) total FROM evaluasi GROUP BY target_id,triwulan');foreach($mapStmt->fetchAll() as $row)$evaluationMap[(int)$row['target_id'].'-'.(int)$row['triwulan']]=(int)$row['total'];
$evalQuery='SELECT e.*,t.indikator,u.nama owner_nama,u.role owner_role FROM evaluasi e JOIN target_kinerja t ON t.id=e.target_id LEFT JOIN users u ON u.id=t.user_id WHERE t.tahun=:tahun';$evalParams=['tahun'=>$tahun];
if($canViewAll&&$selectedUserId>0){$evalQuery.=' AND t.user_id=:user_id';$evalParams['user_id']=$selectedUserId;}elseif(!$canViewAll){$evalQuery.=' AND t.user_id=:user_id';$evalParams['user_id']=(int)$user['id'];}$evalQuery.=' ORDER BY e.created_at DESC,e.id DESC';$evalStmt=db()->prepare($evalQuery);$evalStmt->execute($evalParams);$evaluations=$evalStmt->fetchAll();
render_header('Evaluasi Kinerja (EvKin)'); ?>
<style>.evkin-analysis-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;grid-column:1/-1}.evkin-analysis-grid label{margin:0}.evkin-analysis-grid textarea{min-height:120px}.evkin-history{display:grid;grid-template-columns:repeat(2,minmax(180px,1fr));gap:8px}.evkin-history div{padding:9px;border-radius:9px;background:#f8fafc}.evkin-history strong{display:block;color:#065f46;margin-bottom:4px}@media(max-width:720px){.evkin-analysis-grid,.evkin-history{grid-template-columns:1fr}}</style>
<section class="panel analysis-rule"><strong>Analisis EvKin per Pengguna</strong><p>Setiap pengguna mengisi analisis untuk indikator miliknya. Analisis dipisah menjadi Kendala, Upaya, Strategi, dan Solusi agar mudah dibaca dan ditindaklanjuti.</p></section>
<form method="get" class="toolbar"><input type="hidden" name="page" value="evaluasi"><label>Tahun<input type="number" name="tahun" min="2020" max="2100" value="<?= h((string)$tahun) ?>"></label><?php if($canViewAll):?><label>Pemilik Data<select name="user_id"><option value="0">Semua Pengguna</option><?php foreach($owners as $owner):?><option value="<?= h((string)$owner['id']) ?>" <?= (int)$owner['id']===$selectedUserId?'selected':'' ?>><?= format_user_label($owner['nama']??'',$owner['role']??'',false) ?></option><?php endforeach;?></select></label><?php endif;?><label>Periode<select name="triwulan"><?php for($i=1;$i<=12;$i++):?><option value="<?= $i ?>" <?= $i===$selectedTw?'selected':'' ?>>Bulan <?= $i ?></option><?php endfor;?></select></label><button class="secondary">Tampilkan</button></form>
<section class="panel"><h2>Kewajiban Analisis Bulan <?= $selectedTw ?></h2><div class="table-responsive data-scroll"><table><thead><tr><?php if($canViewAll):?><th>Pemilik</th><?php endif;?><th>Indikator</th><th>Capaian</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if(!$targets):?><tr><td colspan="<?= $canViewAll?5:4 ?>">Belum ada target kinerja.</td></tr><?php endif;?><?php foreach($targets as $target):$trend=achievement_trend($target,$selectedTw);$has=($evaluationMap[(int)$target['id'].'-'.$selectedTw]??0)>0;?><tr><?php if($canViewAll):?><td><?= format_user_label($target['owner_nama']??'',$target['owner_role']??'',true) ?></td><?php endif;?><td><?= h((string)$target['indikator']) ?><br><small><?= h((string)($target['sumber_data']?:'Sumber belum diisi')) ?></small></td><td><?= h((string)$trend['current']) ?>%</td><td><span class="small-badge"><?= $has?'Analisis tersedia':'Belum dianalisis' ?></span></td><td><a class="button secondary" href="index.php?page=evaluasi&tahun=<?= $tahun ?>&triwulan=<?= $selectedTw ?>&target_id=<?= h((string)$target['id']) ?><?= $selectedUserId>0?'&user_id='.h((string)$selectedUserId):'' ?>#form-evkin">Isi Analisis</a></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel" id="form-evkin"><h2>Form Analisis</h2><form method="post" class="form-grid"><input type="hidden" name="tahun" value="<?= $tahun ?>"><input type="hidden" name="user_id" value="<?= $selectedUserId ?>"><label>Indikator<select name="target_id" required><?php foreach($targets as $target):?><option value="<?= h((string)$target['id']) ?>" <?= (int)($_GET['target_id']??0)===(int)$target['id']?'selected':'' ?>><?= h((string)$target['indikator']) ?><?= $canViewAll?' - '.h((string)($target['owner_nama']??'-')):'' ?></option><?php endforeach;?></select></label><label>Periode<select name="triwulan"><?php for($i=1;$i<=12;$i++):?><option value="<?= $i ?>" <?= $i===$selectedTw?'selected':'' ?>>Bulan <?= $i ?></option><?php endfor;?></select></label><div class="evkin-analysis-grid"><label>Kendala<textarea name="kendala" required placeholder="Jelaskan hambatan atau penyebab deviasi capaian."></textarea></label><label>Upaya<textarea name="upaya" required placeholder="Jelaskan upaya yang sudah dilakukan."></textarea></label><label>Strategi<textarea name="strategi" required placeholder="Jelaskan strategi perbaikan periode berikutnya."></textarea></label><label>Solusi<textarea name="solusi" required placeholder="Jelaskan solusi konkret dan tindak lanjut."></textarea></label></div><button type="submit" <?= !$targets?'disabled':'' ?>>Simpan Analisis</button></form></section>
<section class="panel"><h2>Riwayat Analisis</h2><div class="table-responsive data-scroll"><table><thead><tr><th>Waktu</th><?php if($canViewAll):?><th>Pemilik</th><?php endif;?><th>Indikator</th><th>Periode</th><th>Analisis</th></tr></thead><tbody><?php if(!$evaluations):?><tr><td colspan="<?= $canViewAll?5:4 ?>">Belum ada analisis.</td></tr><?php endif;?><?php foreach($evaluations as $evaluation):$a=evkin_decode_analysis((string)$evaluation['narasi']);?><tr><td><?= h((string)$evaluation['created_at']) ?></td><?php if($canViewAll):?><td><?= format_user_label($evaluation['owner_nama']??'',$evaluation['owner_role']??'',true) ?></td><?php endif;?><td><?= h((string)$evaluation['indikator']) ?></td><td>Bulan <?= h((string)$evaluation['triwulan']) ?></td><td><div class="evkin-history"><?php foreach(['kendala'=>'Kendala','upaya'=>'Upaya','strategi'=>'Strategi','solusi'=>'Solusi'] as $key=>$label):?><div><strong><?= $label ?></strong><?= nl2br(h((string)$a[$key])) ?></div><?php endforeach;?></div></td></tr><?php endforeach;?></tbody></table></div></section>
<?php render_footer(); ?>
